/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modelo;

import Logica.Cliente;
import Logica.Controlador;
import Logica.DetallePedido;
import Logica.Pedidos;
import Logica.PedidosDAO;
import Logica.ProductoDAO;
import Logica.Repartidor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class Carrito extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    double tpagar;
    int item;
    int idp;
    int cant;
    double pre;

    Cliente cli = new Cliente();
    Controlador con = new Controlador();
    PedidosDAO vdao = new PedidosDAO();
    Pedidos v = new Pedidos();
    DetallePedido dv = new DetallePedido();
    Repartidor e = new Repartidor();

    private Timer tiempo;
    int cont;
    public final static int TWO_SECOND = 10;

    public Carrito() {
        initComponents();
        setLocation(700, 20);
        //this.setLocationRelativeTo(null);
        Barra.setVisible(false);

        calculatTotal();
        fecha();

        txtCliente.setText(con.DevolverDatosSql("select id from cliente where nombre='" + IniciarSesionCliente.labeldni.getText() + "'", 1));

    }

    void fecha() {
        Calendar calendar = new GregorianCalendar();
        txtFecha.setText("" + calendar.get(Calendar.YEAR) + "-" + calendar.get(Calendar.MONTH) + "-" + calendar.get(Calendar.DAY_OF_MONTH));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDetalle = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRepartidor = new javax.swing.JTextField();
        txtTotalaPagar = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        TipoPago = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Barra = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Restaurante", "Precio", "Nombre", "Tipo", "Cantidad"
            }
        ));
        TablaDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDetalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDetalle);
        if (TablaDetalle.getColumnModel().getColumnCount() > 0) {
            TablaDetalle.getColumnModel().getColumn(0).setMinWidth(40);
            TablaDetalle.getColumnModel().getColumn(0).setPreferredWidth(40);
            TablaDetalle.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 500, 130));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("FECHA :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("MI PEDIDO ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("TIPO DE PAGO :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        txtRepartidor.setBackground(new java.awt.Color(255, 255, 255));
        txtRepartidor.setForeground(new java.awt.Color(0, 0, 0));
        txtRepartidor.setText("1");
        txtRepartidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepartidorActionPerformed(evt);
            }
        });
        getContentPane().add(txtRepartidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 280, -1));

        txtTotalaPagar.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtTotalaPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, 110, -1));

        txtFecha.setBackground(new java.awt.Color(255, 255, 255));
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 280, -1));

        TipoPago.setBackground(new java.awt.Color(255, 255, 255));
        TipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));
        TipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoPagoActionPerformed(evt);
            }
        });
        getContentPane().add(TipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 280, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("REPARTIDOR : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/entrega1.png"))); // NOI18N
        jButton1.setText("GENERAR PEDIDO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/MONOCROMATICO_1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("ID CLIENTE :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtCliente.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 280, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Dinero (2).jpg"))); // NOI18N
        jLabel14.setText("TOTAL A PAGAR :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, -1, -1));
        getContentPane().add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 500, 40));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("ELIMINAR PEDIDO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDetalleMouseClicked

    }//GEN-LAST:event_TablaDetalleMouseClicked

    private void TipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoPagoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtTotalaPagar.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar Datos");
        } else {
            Barra.setVisible(true);
            cont = -1;
            Barra.setValue(0);
            Barra.setStringPainted(true);
            tiempo = new Timer(TWO_SECOND, new TimerListener());
            activar();

            JOptionPane.showMessageDialog(this, "Pedido en camino");
            guardarVenta();
            guardarDetalle();
            JOptionPane.showMessageDialog(this, "Se Realizo con Exito");
            limpiarTabla();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtRepartidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepartidorActionPerformed

    }//GEN-LAST:event_txtRepartidorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) TablaDetalle.getModel();
        int fila = TablaDetalle.getRowCount();
        for (int i = fila - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    void calculatTotal() {
        tpagar = 0;
        for (int i = 0; i < TablaDetalle.getRowCount(); i++) {
            pre = Double.parseDouble(TablaDetalle.getValueAt(i, 2).toString());
            cant = Integer.parseInt(TablaDetalle.getValueAt(i, 5).toString());
            tpagar = tpagar + (cant * pre);
        }
        txtTotalaPagar.setText("" + tpagar + "0");
    }

    void guardarVenta() {
        int idv = Integer.parseInt(txtRepartidor.getText());
        int idc = Integer.parseInt(txtCliente.getText());
        String fecha = txtFecha.getText();
        double total = Double.parseDouble(txtTotalaPagar.getText());
        v.setIdCliente(idc);
        v.setCi_idRepartidor(idv);
        v.setFecha(fecha);
        v.setTotal(total);
        vdao.GuardarVentas(v);

    }

    void guardarDetalle() {
        String idv = vdao.IdVentas();
        int idve = Integer.parseInt(idv);
        for (int i = 0; i < TablaDetalle.getRowCount(); i++) {
            int idp = Integer.parseInt(TablaDetalle.getValueAt(i, 0).toString());
            int cant = Integer.parseInt(TablaDetalle.getValueAt(i, 5).toString());
            double pre = Double.parseDouble(TablaDetalle.getValueAt(i, 2).toString());
            dv.setIdPedido(idve);
            dv.setIdProducto(idp);
            dv.setCantidad(cant);
            dv.setPreUnitario(pre);
            vdao.GuardarDetalleVentas(dv);
        }
    }

    void limpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) TablaDetalle.getModel();
        modelo.setRowCount(0);
        txtTotalaPagar.setText("");
    }

    /**
     * @param args the command line arguments
     */
    class TimerListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            cont++;
            Barra.setValue(cont);
            if (cont == 100) {
                tiempo.stop();
                //esconder();

            }
        }
    }

    public void esconder() {
        this.setVisible(false);
    }

    public void activar() {
        tiempo.start();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Barra;
    public static javax.swing.JTable TablaDetalle;
    private javax.swing.JComboBox<String> TipoPago;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtFecha;
    public static javax.swing.JTextField txtRepartidor;
    public static javax.swing.JTextField txtTotalaPagar;
    // End of variables declaration//GEN-END:variables
}
